apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-hgjwlqcj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-hgjwlqcj 
  name: go-hgjwlqcj
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-hgjwlqcj
    weight: 100 
